services:

  nginx:
    image: nginx:stable
    volumes:
      - '.:/srv'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    ports:
      - '8080:80'
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - '.:/srv'

  db:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password123}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    volumes:
      - db_data:/var/lib/postgresql/data:rw


volumes:
  db_data:

